//Speed of light in meters per second (m/s).
const c =  299792458.0; export c;

// Euler's number.
const e = 2.71828182845904523536028747135266250; export e;

// Acceleration due to gravity on Earth in meters per second per second (m/s^2).
const g = 9.80665; export g;

// The ratio of a circle's circumference to its diameter.
const pi = 3.14159265358979323846264338327950288; export pi;

// The Planck constant in Joules per Hertz (J/Hz)
const h = 6.62607015/(10**(34.0)); export h;

